// Generated by CoffeeScript 1.6.2
var fs;

fs = require("fs");

console.log(process.memoryUsage());

fs.readdir(__dirname, function(err, files) {
  console.log("");
  if (err) {
    return console.log(err);
  }
  if (!files.length) {
    console.log("No files");
  }
  console.log("   Select which file or directory you want to see\n");
  return file(function(i) {
    var filename;

    return filename = file[i];
  });
});
